name: "Update treadmill deployments data"

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-deployments-data:
    runs-on: ubuntu-latest

    env:
      MDBOOK_VERSION: 0.4.36

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository, and to create issues:
      contents: write
      issues: write

    steps:
    # Clone the book repo
    - uses: actions/checkout@v4

    # Install Nix:
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install mdBook
      run: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
        rustup update
        cargo install --version ${MDBOOK_VERSION} mdbook

    - name: Update the deployments-data.json file and re-generate markdown files
      run: |
        pushd lib
        nix-shell -p nix-prefetch-git --run "nix-prefetch-git --url https://github.com/treadmill-tb/deployments.git --rev refs/heads/main > deployments-data.json"

        rm ../generated/boards-pton-srv0.md
        nix-build --argstr site pton-srv0 site-info-md.nix
        cat result > ../generated/boards-pton-srv0.md

        rm -f result
        popd

    - name: Test mdbook build
      run: mdbook build

    # Commit changes back to repo:
    - uses: stefanzweifel/git-auto-commit-action@v5
      if: always() # Run even if the script reported errors
      with:
        commit_message: Update lib/deployments-data.json and regenerate Markdown files
        commit_user_name: Treadmill Book Bot
        commit_user_email: bookbot@treadmill.ci
        commit_author: Treadmill Book Bot <bookbot@treadmill.ci>
